// lib/dummyData.ts

import { Film } from "../../types/film";
import { Character } from "../../types/character";

export const dummyFilms: Film[] = [
  {
    id: "1",
    title: "The Matrix",
    releaseDate: "1999-03-31",
    director: "The Wachowskis",
    episodeID: 1,
    characters: [
      {
        name: "Neo",
        gender: "Pria",
        birthYear: "1962",
        height: "6'1\"",
        mass: "180 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Trinity",
        gender: "Wanita",
        birthYear: "1967",
        height: "5'8\"",
        mass: "130 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Morpheus",
        gender: "Pria",
        birthYear: "1965",
        height: "6'0\"",
        mass: "190 lbs",
        homeworld: "Bumi",
      },
    ],
  },
  {
    id: "2",
    title: "Inception",
    releaseDate: "2010-07-16",
    director: "Christopher Nolan",
    episodeID: 2,
    characters: [
      {
        name: "Dom Cobb",
        gender: "Pria",
        birthYear: "1980",
        height: "5'10\"",
        mass: "175 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Robert Fischer",
        gender: "Pria",
        birthYear: "1985",
        height: "5'11\"",
        mass: "185 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Ariadne",
        gender: "Wanita",
        birthYear: "1992",
        height: "5'6\"",
        mass: "120 lbs",
        homeworld: "Bumi",
      },
    ],
  },
  {
    id: "3",
    title: "Interstellar",
    releaseDate: "2014-11-07",
    director: "Christopher Nolan",
    episodeID: 3,
    characters: [
      {
        name: "Cooper",
        gender: "Pria",
        birthYear: "1970",
        height: "6'0\"",
        mass: "185 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Dr. Amelia Brand",
        gender: "Wanita",
        birthYear: "1980",
        height: "5'9\"",
        mass: "140 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Dr. Mann",
        gender: "Pria",
        birthYear: "1968",
        height: "5'11\"",
        mass: "190 lbs",
        homeworld: "Bumi",
      },
    ],
  },
  {
    id: "4",
    title: "Star Wars: A New Hope",
    releaseDate: "1977-05-25",
    director: "George Lucas",
    episodeID: 4,
    characters: [
      {
        name: "Luke Skywalker",
        gender: "Pria",
        birthYear: "1975",
        height: "5'9\"",
        mass: "165 lbs",
        homeworld: "Tatooine",
      },
      {
        name: "Princess Leia",
        gender: "Wanita",
        birthYear: "1976",
        height: "5'1\"",
        mass: "120 lbs",
        homeworld: "Alderaan",
      },
      {
        name: "Han Solo",
        gender: "Pria",
        birthYear: "1972",
        height: "6'1\"",
        mass: "180 lbs",
        homeworld: "Corellia",
      },
    ],
  },
  {
    id: "5",
    title: "The Dark Knight",
    releaseDate: "2008-07-18",
    director: "Christopher Nolan",
    episodeID: 5,
    characters: [
      {
        name: "Bruce Wayne",
        gender: "Pria",
        birthYear: "1982",
        height: "6'2\"",
        mass: "210 lbs",
        homeworld: "Gotham City",
      },
      {
        name: "Joker",
        gender: "Pria",
        birthYear: "1969",
        height: "6'0\"",
        mass: "180 lbs",
        homeworld: "Gotham City",
      },
      {
        name: "Rachel Dawes",
        gender: "Wanita",
        birthYear: "1983",
        height: "5'7\"",
        mass: "130 lbs",
        homeworld: "Gotham City",
      },
    ],
  },
  {
    id: "6",
    title: "Avengers: Endgame",
    releaseDate: "2019-04-26",
    director: "Anthony Russo, Joe Russo",
    episodeID: 6,
    characters: [
      {
        name: "Iron Man",
        gender: "Pria",
        birthYear: "1970",
        height: "6'1\"",
        mass: "225 lbs",
        homeworld: "Earth",
      },
      {
        name: "Captain America",
        gender: "Pria",
        birthYear: "1918",
        height: "6'2\"",
        mass: "240 lbs",
        homeworld: "Earth",
      },
      {
        name: "Black Widow",
        gender: "Wanita",
        birthYear: "1984",
        height: "5'3\"",
        mass: "130 lbs",
        homeworld: "Earth",
      },
    ],
  },
  {
    id: "7",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    releaseDate: "2001-12-19",
    director: "Peter Jackson",
    episodeID: 7,
    characters: [
      {
        name: "Frodo Baggins",
        gender: "Pria",
        birthYear: "2980",
        height: "3'6\"",
        mass: "80 lbs",
        homeworld: "Shire",
      },
      {
        name: "Aragorn",
        gender: "Pria",
        birthYear: "2965",
        height: "6'0\"",
        mass: "190 lbs",
        homeworld: "Gondor",
      },
      {
        name: "Gandalf",
        gender: "Pria",
        birthYear: "1000",
        height: "5'6\"",
        mass: "160 lbs",
        homeworld: "Valinor",
      },
    ],
  },
  {
    id: "8",
    title: "Jurassic Park",
    releaseDate: "1993-06-11",
    director: "Steven Spielberg",
    episodeID: 8,
    characters: [
      {
        name: "Dr. Alan Grant",
        gender: "Pria",
        birthYear: "1962",
        height: "6'0\"",
        mass: "180 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Dr. Ellie Sattler",
        gender: "Wanita",
        birthYear: "1965",
        height: "5'7\"",
        mass: "130 lbs",
        homeworld: "Bumi",
      },
      {
        name: "John Hammond",
        gender: "Pria",
        birthYear: "1940",
        height: "5'9\"",
        mass: "170 lbs",
        homeworld: "Bumi",
      },
    ],
  },
  {
    id: "9",
    title: "The Lion King",
    releaseDate: "1994-06-15",
    director: "Roger Allers, Rob Minkoff",
    episodeID: 9,
    characters: [
      {
        name: "Simba",
        gender: "Pria",
        birthYear: "1990",
        height: "3'5\"",
        mass: "150 lbs",
        homeworld: "Savanna",
      },
      {
        name: "Mufasa",
        gender: "Pria",
        birthYear: "1965",
        height: "5'8\"",
        mass: "250 lbs",
        homeworld: "Savanna",
      },
      {
        name: "Nala",
        gender: "Wanita",
        birthYear: "1992",
        height: "3'4\"",
        mass: "120 lbs",
        homeworld: "Savanna",
      },
    ],
  },
  {
    id: "10",
    title: "Titanic",
    releaseDate: "1997-12-19",
    director: "James Cameron",
    episodeID: 10,
    characters: [
      {
        name: "Jack Dawson",
        gender: "Pria",
        birthYear: "1975",
        height: "6'1\"",
        mass: "160 lbs",
        homeworld: "Wisconsin",
      },
      {
        name: "Rose DeWitt Bukater",
        gender: "Wanita",
        birthYear: "1980",
        height: "5'8\"",
        mass: "130 lbs",
        homeworld: "Philadelphia",
      },
      {
        name: "Caledon 'Cal' Hockley",
        gender: "Pria",
        birthYear: "1972",
        height: "6'0\"",
        mass: "180 lbs",
        homeworld: "Philadelphia",
      },
    ],
  },
  {
    id: "11",
    title: "The Godfather",
    releaseDate: "1972-03-24",
    director: "Francis Ford Coppola",
    episodeID: 11,
    characters: [
      {
        name: "Vito Corleone",
        gender: "Pria",
        birthYear: "1885",
        height: "5'8\"",
        mass: "185 lbs",
        homeworld: "Sicily",
      },
      {
        name: "Michael Corleone",
        gender: "Pria",
        birthYear: "1920",
        height: "5'11\"",
        mass: "180 lbs",
        homeworld: "New York",
      },
      {
        name: "Kay Adams",
        gender: "Wanita",
        birthYear: "1923",
        height: "5'5\"",
        mass: "130 lbs",
        homeworld: "New York",
      },
    ],
  },
  {
    id: "12",
    title: "Pulp Fiction",
    releaseDate: "1994-10-14",
    director: "Quentin Tarantino",
    episodeID: 12,
    characters: [
      {
        name: "Vincent Vega",
        gender: "Pria",
        birthYear: "1965",
        height: "6'0\"",
        mass: "175 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Jules Winnfield",
        gender: "Pria",
        birthYear: "1960",
        height: "6'2\"",
        mass: "200 lbs",
        homeworld: "Bumi",
      },
      {
        name: "Mia Wallace",
        gender: "Wanita",
        birthYear: "1967",
        height: "5'5\"",
        mass: "130 lbs",
        homeworld: "Bumi",
      },
    ],
  },
  {
    id: "13",
    title: "The Shawshank Redemption",
    releaseDate: "1994-09-22",
    director: "Frank Darabont",
    episodeID: 13,
    characters: [
      {
        name: "Andy Dufresne",
        gender: "Pria",
        birthYear: "1965",
        height: "6'2\"",
        mass: "190 lbs",
        homeworld: "Maine",
      },
      {
        name: "Ellis 'Red' Redding",
        gender: "Pria",
        birthYear: "1948",
        height: "6'0\"",
        mass: "200 lbs",
        homeworld: "Maine",
      },
      {
        name: "Brooks Hatlen",
        gender: "Pria",
        birthYear: "1922",
        height: "5'9\"",
        mass: "160 lbs",
        homeworld: "Maine",
      },
    ],
  },
  {
    id: "14",
    title: "The Avengers",
    releaseDate: "2012-05-04",
    director: "Joss Whedon",
    episodeID: 14,
    characters: [
      {
        name: "Tony Stark",
        gender: "Pria",
        birthYear: "1970",
        height: "6'1\"",
        mass: "225 lbs",
        homeworld: "Earth",
      },
      {
        name: "Thor",
        gender: "Pria",
        birthYear: "1000",
        height: "6'6\"",
        mass: "250 lbs",
        homeworld: "Asgard",
      },
      {
        name: "Black Widow",
        gender: "Wanita",
        birthYear: "1984",
        height: "5'3\"",
        mass: "130 lbs",
        homeworld: "Earth",
      },
    ],
  },
  {
    id: "15",
    title: "Forrest Gump",
    releaseDate: "1994-07-06",
    director: "Robert Zemeckis",
    episodeID: 15,
    characters: [
      {
        name: "Forrest Gump",
        gender: "Pria",
        birthYear: "1944",
        height: "6'1\"",
        mass: "185 lbs",
        homeworld: "Alabama",
      },
      {
        name: "Jenny Curran",
        gender: "Wanita",
        birthYear: "1948",
        height: "5'6\"",
        mass: "125 lbs",
        homeworld: "Alabama",
      },
      {
        name: "Lieutenant Dan Taylor",
        gender: "Pria",
        birthYear: "1940",
        height: "6'2\"",
        mass: "200 lbs",
        homeworld: "Alabama",
      },
    ],
  },
  {
    id: "16",
    title: "Gladiator",
    releaseDate: "2000-05-05",
    director: "Ridley Scott",
    episodeID: 16,
    characters: [
      {
        name: "Maximus Decimus Meridius",
        gender: "Pria",
        birthYear: "150",
        height: "6'1\"",
        mass: "210 lbs",
        homeworld: "Roma",
      },
      {
        name: "Commodus",
        gender: "Pria",
        birthYear: "160",
        height: "5'9\"",
        mass: "185 lbs",
        homeworld: "Roma",
      },
      {
        name: "Lucilla",
        gender: "Wanita",
        birthYear: "180",
        height: "5'7\"",
        mass: "130 lbs",
        homeworld: "Roma",
      },
    ],
  },
  {
    id: "17",
    title: "Avatar",
    releaseDate: "2009-12-18",
    director: "James Cameron",
    episodeID: 17,
    characters: [
      {
        name: "Jake Sully",
        gender: "Pria",
        birthYear: "1980",
        height: "6'0\"",
        mass: "200 lbs",
        homeworld: "Earth",
      },
      {
        name: "Neytiri",
        gender: "Wanita",
        birthYear: "1990",
        height: "5'9\"",
        mass: "145 lbs",
        homeworld: "Pandora",
      },
      {
        name: "Dr. Grace Augustine",
        gender: "Wanita",
        birthYear: "1965",
        height: "5'8\"",
        mass: "150 lbs",
        homeworld: "Earth",
      },
    ],
  },
];



export const dummyCharacters: Character[] = [
  {
    name: "Neo",
    gender: "Pria",
    birthYear: "Unknown", // No specific birth year in the film
    height: "6'1\"",
    mass: "180 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "1",
        title: "The Matrix",
        releaseDate: "1999-03-31",
        director: "The Wachowskis",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Trinity",
    gender: "Wanita",
    birthYear: "Unknown", // No specific birth year in the film
    height: "5'8\"",
    mass: "130 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "1",
        title: "The Matrix",
        releaseDate: "1999-03-31",
        director: "The Wachowskis",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Morpheus",
    gender: "Pria",
    birthYear: "Unknown", // No specific birth year in the film
    height: "6'0\"",
    mass: "190 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "1",
        title: "The Matrix",
        releaseDate: "1999-03-31",
        director: "The Wachowskis",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Dom Cobb",
    gender: "Pria",
    birthYear: "1980",
    height: "5'10\"",
    mass: "175 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "2",
        title: "Inception",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Robert Fischer",
    gender: "Pria",
    birthYear: "1985",
    height: "5'11\"",
    mass: "185 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "2",
        title: "Inception",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Ariadne",
    gender: "Wanita",
    birthYear: "1992",
    height: "5'6\"",
    mass: "120 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "2",
        title: "Inception",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Cooper",
    gender: "Pria",
    birthYear: "1970",
    height: "6'0\"",
    mass: "185 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "3",
        title: "Interstellar",
        releaseDate: "2014-11-07",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Dr. Amelia Brand",
    gender: "Wanita",
    birthYear: "1980",
    height: "5'9\"",
    mass: "140 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "3",
        title: "Interstellar",
        releaseDate: "2014-11-07",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Dr. Mann",
    gender: "Pria",
    birthYear: "1968",
    height: "5'11\"",
    mass: "190 lbs",
    homeworld: "Bumi",
    films: [
      {
        id: "3",
        title: "Interstellar",
        releaseDate: "2014-11-07",
        director: "Christopher Nolan",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Luke Skywalker",
    gender: "Pria",
    birthYear: "1975",
    height: "5'9\"",
    mass: "165 lbs",
    homeworld: "Tatooine",
    films: [
      {
        id: "4",
        title: "Star Wars: A New Hope",
        releaseDate: "1977-05-25",
        director: "George Lucas",
        episodeID: 4,
      },
    ],
  },
  {
    name: "Princess Leia",
    gender: "Wanita",
    birthYear: "1976",
    height: "5'1\"",
    mass: "120 lbs",
    homeworld: "Alderaan",
    films: [
      {
        id: "4",
        title: "Star Wars: A New Hope",
        releaseDate: "1977-05-25",
        director: "George Lucas",
        episodeID: 4,
      },
    ],
  },
  {
    name: "Han Solo",
    gender: "Pria",
    birthYear: "1972",
    height: "6'1\"",
    mass: "180 lbs",
    homeworld: "Corellia",
    films: [
      {
        id: "4",
        title: "Star Wars: A New Hope",
        releaseDate: "1977-05-25",
        director: "George Lucas",
        episodeID: 4,
      },
    ],
  },
  {
    name: "Bruce Wayne",
    gender: "Pria",
    birthYear: "1982",
    height: "6'2\"",
    mass: "210 lbs",
    homeworld: "Gotham City",
    films: [
      {
        id: "5",
        title: "The Dark Knight",
        releaseDate: "2008-07-18",
        director: "Christopher Nolan",
        episodeID: 2,
      },
    ],
  },
  {
    name: "Joker",
    gender: "Pria",
    birthYear: "1969",
    height: "6'0\"",
    mass: "180 lbs",
    homeworld: "Gotham City",
    films: [
      {
        id: "5",
        title: "The Dark Knight",
        releaseDate: "2008-07-18",
        director: "Christopher Nolan",
        episodeID: 2,
      },
    ],
  },
  {
    name: "Rachel Dawes",
    gender: "Wanita",
    birthYear: "1983",
    height: "5'7\"",
    mass: "130 lbs",
    homeworld: "Gotham City",
    films: [
      {
        id: "5",
        title: "The Dark Knight",
        releaseDate: "2008-07-18",
        director: "Christopher Nolan",
        episodeID: 2,
      },
    ],
  },
  {
    name: "Iron Man",
    gender: "Pria",
    birthYear: "1970",
    height: "6'1\"",
    mass: "225 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "6",
        title: "Iron Man",
        releaseDate: "2008-05-02",
        director: "Jon Favreau",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Captain America",
    gender: "Pria",
    birthYear: "1918",
    height: "6'2\"",
    mass: "240 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "7",
        title: "Captain America: The First Avenger",
        releaseDate: "2011-07-22",
        director: "Joe Johnston",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Black Widow",
    gender: "Wanita",
    birthYear: "1984",
    height: "5'3\"",
    mass: "130 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "7",
        title: "The Avengers",
        releaseDate: "2012-05-04",
        director: "Joss Whedon",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Frodo Baggins",
    gender: "Pria",
    birthYear: "2980",
    height: "3'6\"",
    mass: "80 lbs",
    homeworld: "Shire",
    films: [
      {
        id: "8",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        releaseDate: "2001-12-19",
        director: "Peter Jackson",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Aragorn",
    gender: "Pria",
    birthYear: "2965",
    height: "6'6\"",
    mass: "220 lbs",
    homeworld: "Gondor",
    films: [
      {
        id: "8",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        releaseDate: "2001-12-19",
        director: "Peter Jackson",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Gandalf",
    gender: "Pria",
    birthYear: "Unknown",
    height: "5'10\"",
    mass: "150 lbs",
    homeworld: "Middle-Earth",
    films: [
      {
        id: "8",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        releaseDate: "2001-12-19",
        director: "Peter Jackson",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Dr. Alan Grant",
    gender: "Pria",
    birthYear: "1965",
    height: "6'1\"",
    mass: "200 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "9",
        title: "Jurassic Park",
        releaseDate: "1993-06-11",
        director: "Steven Spielberg",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Dr. Ellie Sattler",
    gender: "Wanita",
    birthYear: "1970",
    height: "5'6\"",
    mass: "125 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "9",
        title: "Jurassic Park",
        releaseDate: "1993-06-11",
        director: "Steven Spielberg",
        episodeID: 1,
      },
    ],
  },
  {
    name: "John Hammond",
    gender: "Pria",
    birthYear: "1920",
    height: "5'10\"",
    mass: "185 lbs",
    homeworld: "Earth",
    films: [
      {
        id: "9",
        title: "Jurassic Park",
        releaseDate: "1993-06-11",
        director: "Steven Spielberg",
        episodeID: 1,
      },
    ],
  },
  {
    name: "Simba",
    gender: "Pria",
    birthYear: "Unknown",
    height: "4'6\"",
    mass: "140 lbs",
    homeworld: "Pride Rock",
    films: [
      {
        id: "10",
        title: "The Lion King",
        releaseDate: "1994-06-24",
        director: "Roger Allers, Rob Minkoff",
        episodeID: 1,
      },
    ],
  },
];
